//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int PhoneNumberID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
